# Generated by Django 5.2.3 on 2025-07-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0006_topic_is_public_topic_share_expire_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="可选：上传与条目相关的视频（支持MP4、WebM格式）",
                null=True,
                upload_to="entry_media/videos/%Y/%m/%d/",
                verbose_name="条目视频",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="可选：上传与条目相关的图片",
                null=True,
                upload_to="entry_media/images/%Y/%m/%d/",
                verbose_name="条目图片",
            ),
        ),
    ]
