# Generated by Django 5.2.3 on 2025-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0008_alter_comment_options_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="entry_media/images/%Y/%m/%d/",
                verbose_name="条目图片",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.TextField(verbose_name="条目内容"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="entry_media/videos/%Y/%m/%d/",
                verbose_name="条目视频",
            ),
        ),
    ]
