# Generated by Django 5.2.3 on 2025-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0009_alter_entry_date_added_alter_entry_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="可选：上传音频文件（支持MP3、WAV格式）",
                null=True,
                upload_to="entry_media/audio/%Y/%m/%d/",
                verbose_name="条目音频",
            ),
        ),
    ]
