# Generated by Django 5.2.3 on 2025-07-15 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0010_entry_audio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookmarked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="收藏时间"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="learning_logs.entry",
                        verbose_name="被收藏条目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "条目收藏",
                "verbose_name_plural": "条目收藏",
                "ordering": ["-bookmarked_at"],
                "unique_together": {("user", "entry")},
            },
        ),
    ]
